name: galspecfitx
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy==6.0.0
  - cvxopt==1.3.2
  - matplotlib==3.8.2
  - numpy==1.26.2
  - pip
  - pip:
    - ppxf==9.1.1
    - spectres==2.2.0
    - plotly==5.22.0
