name: galspecfitx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - numpy=1.26.2
  - scipy>=1.14.1
  - matplotlib=3.8.2
  - astropy=6.0.0
  - cvxopt=1.3.2
  - pip
  - pip:
    - ppxf==9.1.1
    - spectres==2.2.0
    - plotly==5.22.0
    - dust-extinction>=1.5.1
